version: '3'

services:
  db_initial:
    container_name: db_initial
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data
      - ./data/databases/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432

  db_final:
    container_name: db_final
    image: postgres:12
    environment:
      POSTGRES_DB: northwind_final
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./data/dbdata_final:/var/lib/postgresql/data
      - ./data/databases/northwind_final.sql:/docker-entrypoint-initdb.d/northwind_final.sql
    ports:
      - 5433:5432